-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 16:51:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema empresa_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_1` DEFAULT CHARACTER SET utf8 ;
USE `empresa_1` ;

-- -----------------------------------------------------
-- Table `empresa_1`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_1`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `date_create` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_1`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_1`.`trabajador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `correo` VARCHAR(100) NULL,
  `dni` CHAR(8) NULL,
  `talla` DECIMAL(15,6) NULL,
  `fecha_ingreso` DATE NULL,
  `tipo` ENUM('empleado', 'obrero') NULL,
  `date_create` TIMESTAMP NULL DEFAULT current_timestamp,
  `date_update` DATETIME NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trabajador_area_idx` (`area_id` ASC),
  CONSTRAINT `fk_trabajador_area`
    FOREIGN KEY (`area_id`)
    REFERENCES `empresa_1`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
